version: '2'

services:
  proxy:
    image: nginx:1.15
    ports:
      - '80:80' 
    volumes:
      - ./conf/:/etc/nginx
    networks:
      - wordpress-net

networks:
  wordpress-net:
    external: true