version: '2'

services:

  wordpress:
    build: .
    ports:
      - 8080:80
    links:
      - "mysql"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: /run/secrets/mysql_wordpress_user
      WORDPRESS_DB_PASSWORD: /run/secrets/mysql_pass
    volumes:
      - wordpress-data:/var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: /run/secrets/mysql_wordpress_user
      MYSQL_PASSWORD: /run/secrets/mysql_pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  wordpress-data:
  mysql-data:
